hue/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'blog'
urlpatterns = [
    path('' , views.index , name='index'),
    path('category/<int:pk>', views.category , name ='category'),
    path('view/<int:pk>' , views.view , name = 'view'),
    path('edit/<int:pk>' , views.edit , name = 'edit'),
    path('user/<int:pk>' , views.user , name = 'user'),
    path('user/posts/<int:pk>' , views.author_post , name = 'author_post'),
]+static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

hue/hue/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('blog.urls')),
    path('accounts/' , include('django.contrib.auth.urls'))
]

hue/blog/models.py
from django.db import models
import datetime

class Category(models.Model):
    title = models.CharField(max_length = 30 , help_text='max of 30 characters')
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='media/category_image' , blank=True , null = True)
    about= models.CharField(max_length = 100 , help_text = "max of 100 characters" , blank = True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

class Author(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    display_image = models.ImageField(upload_to='media/dp' , blank=True , null = True)
    cover_image = models.ImageField(upload_to='media/cover' , blank=True , null = True)
    about = models.TextField()
    

    def __str__(self):
        return self.first_name +" "+ self.last_name 
class Post(models.Model):
    title = models.CharField(max_length = 30 , help_text='max of 30 characters')
    story = models.TextField(blank=True)
    image = models.ImageField(upload_to='media/post' , blank=True , null = True)
    category = models.ForeignKey(Category , on_delete = models.CASCADE , null = True)
    author = models.ForeignKey(Author , on_delete = models.CASCADE , null = True)

    def __str__(self):
        return  self.title
    
    

hue/blog/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    
    class Meta:
        model =Post
        fields = ('title' , 'story' , 'image')

hue/blog/views.py
from django.shortcuts import render , get_object_or_404 , redirect , get_list_or_404
from .models import *
from .forms import *
from django.contrib import messages
import random
# Create your views here.
def index(request):
    post = Post.objects.all()
    category  = Category.objects.all()
    return render(request , 'blog/index.html' , {'post':post , 'category':category, })

def category(request, pk):
    category_name = Category.objects.filter(id = pk)
    post = Post.objects.filter(category_id = pk)
    return render(request , 'blog/category.html', {'post':post , 'category_name': category_name})

def view(request , pk ):
    ran = random.randint(1 , 10)
    recommended = Post.objects.all()
    post = get_object_or_404(Post , pk=pk)
    return render(request , 'blog/view.html' , {'post':post , 'recommended':recommended , 'ran':ran})

def edit(request , pk):
    post = get_object_or_404(Post , pk=pk)
    if request.method =='POST':
        form = PostForm(request.POST, instance = post)

        if form.is_valid():
            form.save()
            messages.success(request , "Successfully edited")
            return redirect('blog:view' , pk=post.pk)
            
    else:
        form = PostForm(instance = post)
        
    return render(request , 'blog/edit.html' , {'form':form})

def user(request , pk):
    post = get_object_or_404(Author , pk=pk)
    return render(request , 'blog/user.html' , {'post':post})

def author_post(request , pk):
    posts = Post.objects.filter(author_id = pk)
    post= get_list_or_404(posts)
    return render(request , 'blog/author_posts.html' , {'post':post})

hue/templates/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'boot.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'mdb.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'material-kit.css'%}">
	<script src="{% static 'jquery.min.js'%}"></script>
    <script src="{% static 'bootstrap.min.js'%}"></script>
    <script src="{% static 'rellax.js'%}"></script>

	<style>
		@font-face{
			font-family: bebas;
			src:url("{%static 'BebasNeue.otf'%}");
		}

		.bb{
			font-family: bebas;
		}

    .flex-container{
      width: 78%;
      margin: 0 auto;
    }
    .change-font{
        font-size: 11em;
    }

    .flex-container-user{
      width: 88%;
      height: 400px;
      margin: 0 auto;
    }

    image-position{
       margin-top: -50px; height: 120px; width: 120px;
    }
    
    .img-gradient {
            position:relative;
            display:inline-block;
        }

        .img-gradient:after {
            content:'';
            position:absolute;
            left:0; top:0;
            width:100%; height:100%;
            display:inline-block;
            background: -moz-linear-gradient(top, rgba(0,47,75,0.5) 0%, rgba(220, 66, 37, 0.5) 100%); /* FF3.6+ */

            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(220, 66, 37, 0.5)), color-stop(100%,rgba(0,47,75,0.5))); /* Chrome,Safari4+ */
            background: -webkit-linear-gradient(top, rgba(0,47,75,0.5) 0%,rgba(220, 66, 37, 0.5) 100%); /* Chrome10+,Safari5.1+ */

            background: -o-linear-gradient(top, rgba(0,47,75,0.5) 0%,rgba(220, 66, 37, 0.5) 100%); /* Opera 11.10+ */

            background: -ms-linear-gradient(top, rgba(0,47,75,0.5) 0%,rgba(220, 66, 37, 0.5) 100%); /* IE10+ */

            background: linear-gradient(to bottom, rgba(0,47,75,0.5) 0%,rgba(220, 66, 37, 0.5) 100%); /* W3C */
            
            }
            .img-gradient img{
                display:block;
            }

            .img-gradient-overlay { /* FF3.6+ */ /* Chrome,Safari4+ */
                background: -webkit-linear-gradient(rgba(0,47,75,0.5) 0%, rgba(220, 66, 37, 0.5) 100%);
                background: -o-linear-gradient(rgba(0,47,75,0.5) 0%, rgba(220, 66, 37, 0.5) 100%);
                background: linear-gradient(rgba(0,47,75,0.5) 0%, rgba(220, 66, 37, 0.5) 100%); 
                border-radius: .3rem;
            }

    @media screen and (max-width:480px){
      .flex-container{
      width: 96%;
      margin: 0 auto;
      }

      .flex-container-user{
      width: 96%;
      height: 260px;
      margin: 0 auto;
    }

    .change-font{
        font-size:2em;
    }
    }
	</style>
</head>
<body>
<nav class="white fixed-top">
	<div class="container">
		<a href="{%url 'blog:index'%}" class="bb header" style="font-size: 26px; color: black;">Blog</a>
		<ul class="hide-on-small-and-down right">
			<li><a href="" class="bb" style="color: black;">New</a></li>
			<li><a href="#" class="bb" style="color: black;">Categories</a></li>
			{%if user.is_authenticated%}
			<li><a href="{%url 'logout'%}" class="bb" style="color: black;">Logout</a></li>
            {%else%}
			<li><a href="{%url 'login'%}" class="bb" style="color: black;">login</a></li>
            <li><a href="" class="bb" style="color: black;">register</a></li>
			{%endif%}
		</ul>
	</div>
</nav>
<div style="width: 100%; padding-top: 45px;"></div>


{%block content%}


{%endblock%}

{%block footer%}
<footer class="page-footer font-small white black-text pt-4 mt-4">
      
          <!--Footer Links-->
          <div class="container text-center text-md-left">

          <div id="map-container-8" class="z-depth-1-half map-container mb-4" style="height: 200px"></div>

      
              <!-- Footer links -->
              <div class="row text-center text-md-left mt-3 pb-3">
      
                  <!--First column-->
                  <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="mb-4 font-weight-bold bb black-text">Blog</h6>
                      <p>Latest in News</p>
                  </div>
                  <!--/.First column-->
      
                  <hr class="w-100 clearfix d-md-none">
      
                  <!--Second column-->
                  <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 black-text">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
                      <p><a href="#!" class="black-text">Gallery</a></p>
                      <p><a href="#!" class="black-text">About Us</a></p>
                      <p><a href="#!" class="black-text">KDF</a></p>
                      <p><a href="#!" class="black-text">Blog</a></p>
                  </div>
                  <!--/.Second column-->
      
                  <hr class="w-100 clearfix d-md-none">
      
                  <!--Third column-->
                  <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                      
                      <p><a href="mailto:jeicanjiko@gmail.com"><i class="fa fa-envelope mr-3 black-text"></i>thekansoul@gmail.com</a></p>
                      
                  </div>
                  <!--/.Third column-->
      
                  <hr class="w-100 clearfix d-md-none">
      
                  
      
              </div>
              <!-- Footer links -->
              <hr>
                      
      
              <div class="row py-3 d-flex align-items-center">
      
                  <!--Grid column-->
                  <div class="col-md-8 col-lg-8">
      
                      <!--Copyright-->
                      <p class="text-center text-md-left black-text bb"> 2018 Copyright: the kansoul </p>
                      <!--/.Copyright-->
      
                  </div>
                  <!--Grid column-->
      
                  <!--Grid column-->
                  <div class="col-md-4 col-lg-4 ml-lg-0">
      
                      <!--Social buttons-->
                      <div class="text-center text-md-right">
                          <ul class="list-unstyled list-inline">
                               <li class="list-inline-item"><a class="btn-floating white"><i class="fa fa-facebook"></i></a></li>
                              <li class="list-inline-item"><a class="btn-floating white"><i class="fa fa-share-alt"></i></a></li>
                              <li class="list-inline-item"><a class="btn-floating white" href="#!"><i class="fa fa-envelope"></i></a></li>
                          </ul>
                      </div>
                      <!--/.Social buttons-->
      
                  </div>
                  <!--Grid column-->
      
              </div>
      
          </div></footer>
{%endblock%}
</body>
</html>

hue/templates/blog/author_posts.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block content%}
<div class="container">
		
		<hr>
		<div class="row">
		
		{%for p in post%}
	
		<!-- Grid column -->
		<div class="col-md-4 mb-4">
		  <div class="card card-image" style="background-image: url('{{p.image.url}}');">
			<div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4 rounded">
			  <div>
				<h5 class="red-text">
				  
				  <strong class="bb">{{p.category}}</strong>
				</h5>
				<h3 class="py-3 font-weight-bold">
				  <strong>{{p.title}}</strong>
				</h3>
				<p class="pb-3">{{p.story | truncatewords:"10"}}
				</p>
				<a class="btn btn-danger btn-rounded btn-md" href="{% url 'blog:view' pk=p.pk%}"><i class="fa left"></i> Read More</a>
			  </div>
			</div>
		  </div>
		</div>
		<!-- Grid column -->

		{%endfor%}
	<hr style="width: 90%">
	
	</div>
	</div>
</div>
{%endblock%}

hue/templates/blog/category.html
{%extends 'base.html'%}
{% load staticfiles%}
{%block content%}
<div class="container">
		<h2 class="center"></h2>
		<hr>
	<div class="row">
	
	{%for p in post%}
    <!-- Grid column -->
    <div class="col-md-4 mb-4">
      <div class="card card-image" style="background-image: url('{{p.image.url}}');">
        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4 rounded">
          <div>
            <h class="red-text">
			    <strong class="bb">{{p.category}}</strong>
            </h5>
            <h3 class="py-3 font-weight-bold white-text">
             <strong>{{p.title}}</strong>
            </h3>
            <p class="pb-3 white-text">{{p.story | truncatewords:"20"}}</p>
            <a class="btn btn-danger btn-rounded btn-md" href="{%url 'blog:view' pk=p.pk %}"><i class="fa left"></i> Read More</a>
          </div>
        </div>
      </div>
		</div>
	{%endfor%}
    <!-- Grid column -->


<hr style="width: 90%">

</div>
</div>
{%endblock%}

hue/templates/blog/edit.html
{%extends 'base.html'%}
{% load staticfiles%}

{%block content%}


<div style=" width:100%; height: 4em;"></div>

<div class="container"  style="margin-top: 3em;">
	<div class="main main-raised">
		<div class="card">
				<div class="container">
						<form method="POST">{%csrf_token%}
								<h5><label>Title</label></p5>
								{{form.title}}

								<h5><label>Content</label></p5>
								{{form.story}}

								<h5><label>Image</label></p5>
								{{form.image}}
								<br><br>
								<button class="btn btn-danger" type="submit">Submit</button>
							</form>
				</div>
		</div>
	</div>
</div>
{%endblock%}

<h1>hello</h1>
{%block footer%}{% endblock%}

hue/templates/blog/index.html
{%extends 'base.html'%}
{%load staticfiles%}

{%block content%}
	
	  <div style="width: 98% ; margin: 0 auto; max-width: 1280px;">
	  	<div>
			<img src="{% static 'pop.jpg' %}"  style="height: 70%; width: 100%; z-index: -100;" alt="">
	  		<div class="bb white-text change-font">
				  <div class="bb r" data-rellax-speed=4 style="position: absolute; left: 20%; top: 40%;">b</div>
				  <div class="bb r" data-rellax-speed=5 style="position: absolute; left: 25%; top: 40%;">l</div>
				  <div class="bb r" data-rellax-speed=3 style="position: absolute; left: 30%; top: 40%;">o</div>
				  <div class="bb r" data-rellax-speed=7 style="position: absolute; left: 35%; top: 40%;">g</div>
			  </div>
	  		<h6 class="center white-text"></h6>
	  	</div>
	  </div>



<div style="width: 100% ; height: 10px"></div>

<hr style="width: 90%">
<div style="width: 100% ; height: 8px"></div>
<div class="container">
	<h2 >Categories</h2>
	<hr>
	<div class="row">
		{%for c in category%}
			<!-- <div class="col-md-3">
				<div  class="card card-cascade wider mt-4">
					<div  class="view overlay hm-white-slight waves-light">
						<a href=""><img class="img-fluid" src="{{c.image.url}}"></a>
					</div>
					<div  class="card-body text-center">
					<h4 class="card-title mb-3 font-bold bb"><a href="#!" class="red-text">{{c.title}}</a></h4>
					</div>
				</div>
			</div> -->
			<div class="col-md-3 col-sm-12">
				<div class="card card-image" style="background-image: url('{{c.image.url}}'); background-size: cover;">
					<div class="text-white text-center d-flex align-items-center img-gradient-overlay py-5 px-4">
						<div class="card-body">
							<h3 class="card-title pt-2 bb white-text" ><strong>{{c.title}}</strong></h3>
								<a href ="{%url 'blog:category' pk=c.id%}" class="bb btn btn-deep-orange waves-effect waves-light">View</a>
					</div>
				</div>
				</div>
			</div>			
		{%endfor%}
	</div>
	</div>
</div>


<div class="container">
		<h2 >New Posts</h2>
		<hr>
		<div class="row">
		
		{%for p in post%}
	
		<!-- Grid column -->
		<div class="col-md-4 mb-4">
		  <div class="card card-image" style="background-image: url('{{p.image.url}}');">
			<div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4 rounded">
			  <div>
				<h5 class="red-text">
				  
				  <strong class="bb">{{p.category}}</strong>
				</h5>
				<h3 class="py-3 font-weight-bold">
				  <strong>{{p.title}}</strong>
				</h3>
				<p class="pb-3">{{p.story | truncatewords:"10"}}
				</p>
				<a class="btn btn-danger btn-rounded btn-md" href="{% url 'blog:view' pk=p.pk%}"><i class="fa left"></i> Read More</a>
			  </div>
			</div>
		  </div>
		</div>
		<!-- Grid column -->

		{%endfor%}
	<hr style="width: 90%">
	
	</div>
	</div>
</div>

<script>
	var rel = new Rellax('.r')
	
</script>
{%endblock%}

			<div class="col-md-4">
				<div  class="card card-cascade wider mt-4">
					<div  class="view overlay hm-white-slight waves-light">
						<img  class="img-fluid" src="">
					</div>
					<div  class="card-body text-center">
					<h4  class="card-title mb-3 font-bold"></h4>
					<h6  class="orange-text bb"><strong ></strong></h6>
					<p  class="card-text"></p>
					</div>
				</div>
			</div>

hue/templates/blog/new.html
{%extends 'base.html'%}
{%load staticfiles%}

{%block content%}
<div class="container" style="padding-top: 50px; margin: 0, auto;">
	<div class="col-md-8">
		<form method="POST">
			{%csrf_token%}
			<h6 for="title">Title</h6>
			<div id="title">{{form.title}}</div>

			<h6 >Story</h6>
			<div>{{form.story}}</div>

			{{form.category}}
			{{form.author}}

			<button type="submit" class="btn-large btn-danger">Submit Changes</button>
		</form>
	</div>
</div>
{%endblock%}
{%block footer%}{% endblock%}

hue/templates/blog/user.html
{%extends 'base.html'%}
{%load staticfiles%}

{%block content%}
	<div class="flex-container-user" id="my-user-backgorund">
		<div class="page-header header-filter" data-parallax="true" style="background-image: url('{{post.cover_image.url}}');  background-size: cover; height: 400px; background-repeat:no-repeat;  transform: translate3d(0px, 0px, 0px);"></div>
	</div>
	<div class="container">
		
	<div class="main main-raised">
		
			<div class="container">
				
					<div class="col-md-10 mr-auto ml-auto">

						<img src="{{post.display_image.url}}" class="rounded-circle" style=" margin: -50px 50% 0px auto; height: 130px; width: 130px;">
						<a href="{% url 'blog:index'%}"><img src="{% static 'back.png'%}" style="position: absolute; left: -5%; top: 18%;"></a>
								<div class="name">
									<h2 class=" center">{{post.first_name}} {{post.last_name}}</h2>
									<div class="row" style="justify-content: center;">
										<ul style="display: flex;justify-content: center;">
											<li><a href="#"><img src="{% static 'twitter.png'%}"></a></li>
											<li><a href="#"><img src="{% static 'insta.png'%}"></a></li>
											<li><a href="#"><img src="{% static 'facebook.png'%}"></a></li>
										</ul>
									</div>
								
									<h4 class="center font-weight-bold">Description</h4>
									<hr style="width: 70%;">
									<p class="lead">{{post.about}}</p>
									<div style="width: 100%; height: 30px;"></div>
									<a href="{%url 'blog:author_post' pk=post.pk%}" class="btn btn-danger ">More from Me</a>
									<div style="width: 100%; height: 30px;"></div>
								</div>
							
				
					</div>

					
			</div>			
		
	</div>
	<div style="width: 100%; height: 30px;"></div>

	</div>

{%endblock%}
{%block footer%}{%endblock%}

hue/templates/blog/view.html
{%extends 'base.html'%}
{%load staticfiles%}

{%block content%}
	<div class="flex-container">
		<div  class="row mb-12 pb-4">
			<div class="container" style="margin-top: 50px;">
					{%if messages%}
					<ul class="messages">
						{%for message in messages%}
							
					<div class="alert alert-success alert-dismissable">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
							<strong>Success!</strong> {{message}}
					</div> 
			</div>	
						{%endfor%}
					</ul>
					{%endif%}
			</div>
	
			<div  class="card card-cascade wider reverse my-4 mx-3">
					<div  class="view overlay hm-white-slight">
					<img  class="img-fluid" src="{{post.image.url}}" style="width: 100%; height: 70%;">
					<span><div  class="mask"></div></span>
				</div>

				<div  class="card-body">
					<h4  class="mb-4" style="font-size: 2.1em;">{{post.title}}</h4>
					<h5 class="orange-text bb" style="float: left;"><strong > Category: {{post.category}} </strong></h5><br><br>

					<div class="row">
						<img src="{{post.author.display_image.url}}" style="height: 55px; width: 55px; border-radius: 50%; margin-left: -70px;" >
						<h5 style="margin-left: 10px; margin-top: 20px;">	<a href="{%url 'blog:user' pk=post.author.pk%}" class="red-text"><strong>{{post.author}}</strong></a></h5>
					</div>
					<p  class="card-text" style="font-size:1.3em; text-align: left;">{{post.story}}</p>
						
						<a href="{% url 'blog:index'%}" class="btn btn-danger bb left"> BACK</a>
						<a href="{%url 'blog:edit' pk=post.pk%}" class="btn btn-danger bb" style="float: right;"> Edit</a>
					
						<div style="width: 100%; height: 4em;"></div>
						
						
						<h3 class="center">Recommended</h3>
						<hr style="width: 90%;">
						<div class="row">
							{% for r in recommended%}
								{%if r.category == post.category%}
									{%if r.id != post.id%}
									<div class="col-md-4 mb-4">
											<div class="card card-image" style="background-image: url('{{r.image.url}}');">
											<div class="text-white rgba-black-strong py-5 px-4">
												<div>
												<h5 class="orange-text center">
													
													<strong class="bb">{{r.category}}</strong>
												</h5>
												<h4 class="py-3 center" style="margin:0 auto;">
													{{r.title | truncatewords:"6"}}
												</h4>
												<a class="btn btn-danger bb center" style="margin-left: 55px;" href="{% url 'blog:view' pk=r.pk%}">Read</a>
												</div>
											</div>
											</div>
									</div>
									{%endif%}			
								{%endif%}

							{%empty%}
								<h3 class="center">Sorry, there's no recommended. Click <a href="{%url 'blog:index' %}">here</a> for more though ;)</h3>
							{%endfor%}
						</div>
					
				</div>
			</div>
		</div>
	</div>


{%endblock%}
{%block footer%}{%endblock%}